---
# usage example: 
#   sudo ./install.sh
#   - or -
#   sudo ansible-playbook install.yml -vvvv -c local -i 127.0.0.1,
#         (yes, the comma is necessary)

- hosts: all
  tasks: 
    - name: install dependencies
      yum: state=present name={{ item }}
      with_items:
        - tmux
        - tree

    ### cowsay.yml ###
    - name: check cowsay out from github
      git: repo=https://github.com/schacon/cowsay dest=~/.cowsay

    - name: run the install script
      shell: sh install.sh chdir=~/.cowsay

    ### tmux.yml ###
    - name: install dependencies
      yum: state=present name={{ item }}
      with_items:
        - tmux

    - name: write tmux.conf
      copy: src=tmux.conf dest=~/.tmux.conf

    ### cut here for sane system python ###
    # FIXME
#     - name: install deps (mostly for ncurses/readline)
#       yum: state=present name={{ item }}
#       with_items:
#         - python-devel
#         - ncurses-devel
#         - build-essential
#         - libncursesw5-dev
#         - libssl-dev
#         - libsqlite3-dev
#         - tk-dev
#         - libgdbm-dev
#         - libc6-dev
#         - libbz2-dev
# 
#     - name: install readline support for python -i
#       command: pip install readline

    ### cut here for screen sharing ###
    - name: install vino and vinagre
      yum: state=present name={{ item }}
      with_items: [ 'vino', 'vinagre' ]

    - name: symlink vino-server into /usr/bin
      file: src=/usr/libexec/vino-server dest=/usr/bin/vino-server state=link
    
    ### cut here for silver-searcher.yml ###
    # FIXME
#    - name: fetch dependencies
#      yum: state=present name={{ item }}
#      with_items:
#        - "@pcre-devel"
#        - "@xz-devel"
#        - "pcre-devel"
#        - "lzma-devel"
#
#    - name: clone the silver searcher repo
#      git: repo=https://github.com/ggreer/the_silver_searcher dest=~/src/the_silver_searcher
#
#    - name: run the build script
#      shell: "./build.sh && sudo make install chdir=~/src/the_silver_searcher"

    ### cut here for vim.yml ###
    - name: install vim dependencies
      yum: state=present name={{ item }}
      with_items:
        - vim

    - name: ensure vim directories exist
      file: state=directory name={{ item }}
      with_items:
        - ~/.vim/autoload
        - ~/.vim/bundle

    - name: install vim-pathogen
      copy: src=pathogen.vim dest=~/.vim/autoload/pathogen.vim

    - name: write dotfiles
      template: src={{ item }} dest=~/.{{ item }}
      with_items:
        - vimrc

    - name: fetch vim plugins from github
      git: repo=https://github.com/{{ item }} dest=~/.vim/bundle/{{ item.split("/")[1] }}
      with_items:
#        - rking/ag.vim
        - tpope/vim-fugitive
        - tpope/vim-sensible
        - tpope/vim-markdown
        - tpope/vim-jdaddy
        - tpope/vim-eunuch
