---
# usage example: 
#   sudo ./install.sh
#   - or -
#   sudo ansible-playbook install.yml -vvvv -c local -i 127.0.0.1,
#         (yes, the comma is necessary)

- hosts: all
  tasks: 
    - name: install dependencies
      apt: state=present name={{ item }}
      with_items:
        - tmux
        - tree
        - silversearcher-ag
        - cowsay
        - fonts-inconsolata

    ### cowsay.yml ###
    - name: install rms cowfile
      copy: src=rms.cow dest=/usr/share/cowsay/cows/rms.cow

    - name: set as default ansible cowfile
      lineinfile: dest=/etc/environment line=ANSIBLE_COW_SELECTION=rms.cow

    ### tmux.yml ###
    - name: install dependencies
      apt: state=present name={{ item }}
      with_items:
        - tmux

    - name: write tmux.conf
      copy: src=tmux.conf dest=~/.tmux.conf

    ### cut here for vim.yml ###
    - name: install vim dependencies
      apt: state=present name={{ item }}
      with_items:
        - vim
        - silversearcher-ag

    - name: ensure vim directories exist
      file: state=directory name={{ item }}
      with_items:
        - ~/.vim/autoload
        - ~/.vim/bundle
        - ~/.vim/colors

    - name: install vim colorscheme
      copy: src=lexmurphy.vim dest=~/.vim/colors

    - name: install vim-pathogen
      copy: src=pathogen.vim dest=~/.vim/autoload/pathogen.vim

    - name: write dotfiles
      template: src={{ item }} dest=~/.{{ item }}
      with_items:
        - vimrc

    - name: fetch vim plugins from github
      git: repo=https://github.com/{{ item }} dest=~/.vim/bundle/{{ item.split("/")[1] }}
      with_items:
        - rking/ag.vim
        - tpope/vim-fugitive
        - tpope/vim-sensible
        - tpope/vim-markdown
        - tpope/vim-jdaddy
        - tpope/vim-eunuch
